#!/bin/bash
 
# wget https://gist.github.com/dsandstrom/5753864/raw/subl
if [ "$#" -eq "0" ] ; then
  for file in *sublime-project
  do
    if [ -f $file ] ; then
      # if no arguments, find if there is a project file in the current directory
      filename="${file%.*}"
      echo "Opening project: $filename"
      /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -n $file &
      exit 0
    # else
    #   # if no project file, just open the current directory
    #   echo "Opening current directory"
    #   /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -n "$a" &
    #   exit 0
    fi
  done
fi

# if arguments given, run as normal
/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl $@
exit 0