#!/bin/bash

# Looks for and opens *.sublime-project in dir of singular argument
#   else falls back to standard `subl` call.
#   adapted from https://gist.github.com/dsandstrom/5753864
if [ "$#" -eq "1" ] && [ -d "$1" ] ; then
  for file in ${1%/}/*.sublime-project
  do
    if [ -f $file ] ; then
      # if no arguments, find if there is a project file in the current directory
      filename="${file%.*}"
      echo "Opening project: $filename"
      /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -n $file &
      exit 0
    fi
  done
fi

# if arguments given, run as normal
/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl $@
exit 0